/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.handong.excel.merging;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
